### ISSUE TITLE
Doesn't load in HA 2024.11. 0b1

### ISSUE THREAD

**Issue by Bluhme1** [lichtteil/local_luftdaten#64]
@lichtteil 
Integration does not load in latest HA beta. See error log below:

Logger: homeassistant.components.sensor
Kilde: helpers/entity_platform.py:728
integration: Sensor (dokumentation, problemer)
Første forekomst: 10.07.49 (4 forekomster)
Senest logget: 10.07.49

local_luftdaten: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/local_luftdaten/sensor.py", line 125, in async_update
    await self._rest_client.async_update()
  File "/config/custom_components/local_luftdaten/sensor.py", line 173, in async_update
    with async_timeout.timeout(30):
TypeError: 'Timeout' object does not support the context manager protocol

**Comment by Bluhme1** [comment]
Solved in b2
Closing
